/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and obtain a JWT access token */
        post: operations["AuthController_loginRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account (auto-login returns JWT) */
        post: operations["AuthController_registerRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a resource for an emergency (requires authentication) */
        post: operations["ResourcesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a resource (coordinator only) */
        post: operations["ResourcesController_verifyResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a resource (coordinator only) */
        post: operations["ResourcesController_publishResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/coordination/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the coordination queue for an emergency (coordinator only) */
        get: operations["CoordinationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/public/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published (active) resources for an emergency */
        get: operations["PublicController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active emergencies */
        get: operations["EmergenciesController_list"];
        put?: never;
        /** Create an emergency (admin only) */
        post: operations["EmergenciesController_createEmergency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get emergency by slug */
        get: operations["EmergenciesController_getBySlugRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/needs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a need for an emergency (authenticated requester) */
        post: operations["NeedsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/public/needs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List validated needs for an emergency (public) */
        get: operations["NeedsController_listPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/needs/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pending needs queue for an emergency (coordinator only) */
        get: operations["NeedsController_listQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{needId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a need (coordinator only) */
        post: operations["NeedsController_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{needId}/assign-manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a managing organization to a need (coordinator only) */
        post: operations["NeedsController_assignManager"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organizations (public) */
        get: operations["OrganizationsController_list"];
        put?: never;
        /** Create a new organization (authenticated users) */
        post: operations["OrganizationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations the authenticated user belongs to */
        get: operations["OrganizationsController_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode a free-text address query (Nominatim / OpenStreetMap) */
        get: operations["GeocodingController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated metrics for an emergency (public) */
        get: operations["MetricsController_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example admin@reliefhub.org */
            email: string;
            /** @example admin1234 */
            password: string;
        };
        LoginResponseDto: {
            /** @description JWT access token */
            accessToken: string;
        };
        RegisterDto: {
            /** @example user@reliefhub.org */
            email: string;
            /** @example password123 */
            password: string;
            /** @example Jane Doe */
            name: string;
        };
        RegisterResponseDto: {
            /** @description JWT access token (auto-login after registration) */
            accessToken: string;
        };
        LocationDto: {
            /** @example Calle Mayor 1, Valencia */
            address: string;
            /**
             * @description Latitude between -90 and 90
             * @example 39.4699
             */
            latitude: number;
            /**
             * @description Longitude between -180 and 180
             * @example -0.3763
             */
            longitude: number;
        };
        RegisterResourceDto: {
            /**
             * @example collection_point
             * @enum {string}
             */
            type: "collection_point" | "delivery_point" | "collection_and_delivery" | "warehouse" | "transport" | "supplier" | "venue";
            /**
             * @description Stage of the resource in the emergency supply chain
             * @example origin
             * @enum {string}
             */
            stage: "origin" | "intermediate" | "destination";
            /** @example Cruz Roja Madrid */
            name: string;
            /** @example Centro de acopio principal */
            description?: string;
            /** @description Physical location of the resource */
            location: components["schemas"]["LocationDto"];
            /**
             * Format: uuid
             * @description Organization offering this resource (optional)
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            ownerOrganizationId?: string;
        };
        RegisterResourceResponseDto: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
        };
        VerifyResourceDto: {
            /**
             * @description Must not be "unverified"
             * @example verified
             * @enum {string}
             */
            level: "unverified" | "verified" | "official";
        };
        LocationViewDto: {
            /** @example Calle Mayor 1, Valencia */
            address: string;
            /** @example 39.4699 */
            latitude: number;
            /** @example -0.3763 */
            longitude: number;
        };
        ResourceViewDto: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /**
             * @example collection_point
             * @enum {string}
             */
            type: "collection_point" | "delivery_point" | "collection_and_delivery" | "warehouse" | "transport" | "supplier" | "venue";
            /**
             * @example origin
             * @enum {string}
             */
            stage: "origin" | "intermediate" | "destination";
            /** @example Cruz Roja Madrid */
            name: string;
            /** @example Centro de acopio principal */
            description?: Record<string, never> | null;
            location: components["schemas"]["LocationViewDto"];
            /**
             * @example verified
             * @enum {string}
             */
            verificationLevel: "unverified" | "verified" | "official";
            /**
             * @example active
             * @enum {string}
             */
            publicStatus: "hidden" | "active" | "saturated" | "paused" | "closed";
            /** Format: uuid */
            ownerOrganizationId?: Record<string, never> | null;
        };
        CreateEmergencyDto: {
            /** @example Emergencia sísmica — Venezuela */
            name: string;
            /**
             * @description URL-safe slug (lowercase letters, digits, hyphens). Auto-generated from name if omitted.
             * @example venezuela
             */
            slug?: string;
            /**
             * @description ISO 3166-1 alpha-2 country code
             * @example VE
             */
            country: string;
        };
        CreateEmergencyResponseDto: {
            /** @example 11111111-1111-4111-8111-111111111111 */
            id: string;
            /** @example venezuela */
            slug: string;
        };
        EmergencyViewDto: {
            /** @example 11111111-1111-4111-8111-111111111111 */
            id: string;
            /** @example Emergencia sísmica — Venezuela */
            name: string;
            /** @example venezuela */
            slug: string;
            /** @example VE */
            country: string;
            /** @example active */
            status: string;
        };
        NeedLocationDto: {
            /** @example 123 Main Street, Caracas, Venezuela */
            address: string;
            /**
             * @description Latitude (-90 to 90)
             * @example 10.4806
             */
            latitude: number;
            /**
             * @description Longitude (-180 to 180)
             * @example -66.9036
             */
            longitude: number;
        };
        NeedItemDto: {
            /**
             * @description Name of the item needed
             * @example Water bottles
             */
            name: string;
            /**
             * @description Quantity needed (positive integer)
             * @example 100
             */
            quantity: number;
            /**
             * @description Unit of measurement (optional)
             * @example liters
             */
            unit?: string;
            /**
             * @example water
             * @enum {string}
             */
            category: "hygiene" | "water" | "food" | "medical" | "shelter" | "tools" | "other";
        };
        CreateNeedDto: {
            /** @example Alimentos para 50 familias */
            title: string;
            /** @example Descripción detallada de la necesidad */
            description?: string;
            location: components["schemas"]["NeedLocationDto"];
            /**
             * @example high
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * Format: uuid
             * @description Organization on whose behalf the request is made (optional)
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            requesterOrganizationId?: string;
            /** @description List of items needed (minimum 1) */
            items: components["schemas"]["NeedItemDto"][];
        };
        CreateNeedResponseDto: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
        };
        NeedLocationResponseDto: {
            /** @example 123 Main Street, Caracas */
            address: string;
            /** @example 10.4806 */
            latitude: number;
            /** @example -66.9036 */
            longitude: number;
        };
        NeedItemResponseDto: {
            /** @example Water bottles */
            name: string;
            /** @example 100 */
            quantity: number;
            /** @example liters */
            unit?: Record<string, never> | null;
            /**
             * @example water
             * @enum {string}
             */
            category: "hygiene" | "water" | "food" | "medical" | "shelter" | "tools" | "other";
        };
        NeedViewDto: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /**
             * Format: uuid
             * @example 11111111-1111-4111-8111-111111111111
             */
            emergencyId: string;
            /** @example Alimentos para 50 familias */
            title: string;
            /** @example Descripción detallada */
            description?: Record<string, never> | null;
            location: components["schemas"]["NeedLocationResponseDto"];
            /**
             * @example high
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /** Format: uuid */
            requesterOrganizationId?: Record<string, never> | null;
            /** Format: uuid */
            managingOrganizationId?: Record<string, never> | null;
            items: components["schemas"]["NeedItemResponseDto"][];
            /**
             * @example pending
             * @enum {string}
             */
            status: "pending" | "validated" | "rejected" | "fulfilled";
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
        };
        AssignNeedManagerDto: {
            /**
             * Format: uuid
             * @description ID of the organization that will manage this need
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            organizationId: string;
        };
        CreateOrganizationDto: {
            /** @example Red Cross Spain */
            name: string;
            /**
             * @example ngo
             * @enum {string}
             */
            type: "ngo" | "company" | "public_admin" | "association" | "other";
            /** @example ES-12345678 */
            taxId?: string;
            /** @example contact@org.example */
            contactEmail?: string;
        };
        CreateOrganizationResponseDto: {
            /** @description New organization UUID */
            id: string;
        };
        OrganizationViewDto: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "ngo" | "company" | "public_admin" | "association" | "other";
            verificationLevel: string;
        };
        GeocodeResultDto: {
            /** @example Madrid, Community of Madrid, Spain */
            address: string;
            /**
             * @description Decimal degrees latitude
             * @example 40.4165
             */
            latitude: number;
            /**
             * @description Decimal degrees longitude
             * @example -3.70256
             */
            longitude: number;
        };
        NeedsMetricsDto: {
            /**
             * @description Total needs registered for this emergency
             * @example 10
             */
            total: number;
            /**
             * @description Open needs: pending + validated
             * @example 7
             */
            open: number;
            /**
             * @description Closed needs: fulfilled
             * @example 2
             */
            closed: number;
        };
        ResourcesMetricsDto: {
            /**
             * @description Total resources registered for this emergency
             * @example 5
             */
            total: number;
            /**
             * @description Active logistic points (publicStatus = Active)
             * @example 3
             */
            active: number;
            /**
             * @description Resources pending publication (publicStatus = Hidden)
             * @example 2
             */
            pending: number;
        };
        EmergencyMetricsDto: {
            needs: components["schemas"]["NeedsMetricsDto"];
            resources: components["schemas"]["ResourcesMetricsDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_loginRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourcesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterResourceDto"];
            };
        };
        responses: {
            /** @description Resource registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResourceResponseDto"];
                };
            };
            /** @description Invalid request body or UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourcesController_verifyResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyResourceDto"];
            };
        };
        responses: {
            /** @description Resource verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid verification level or UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourcesController_publishResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource published */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not verified yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoordinationController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of resources in queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceViewDto"][];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinator role required for this emergency */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Emergency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of published resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceViewDto"][];
                };
            };
        };
    };
    EmergenciesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active emergencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyViewDto"][];
                };
            };
        };
    };
    EmergenciesController_createEmergency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmergencyDto"];
            };
        };
        responses: {
            /** @description Emergency created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEmergencyResponseDto"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmergenciesController_getBySlugRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Emergency found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyViewDto"];
                };
            };
            /** @description Emergency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeedsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNeedDto"];
            };
        };
        responses: {
            /** @description Need created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateNeedResponseDto"];
                };
            };
            /** @description Invalid request body or UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeedsController_listPublic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of validated needs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedViewDto"][];
                };
            };
        };
    };
    NeedsController_listQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of pending needs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedViewDto"][];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinator role required for this emergency */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeedsController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Need UUID */
                needId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Need validated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Need is not in pending status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Need not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeedsController_assignManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Need UUID */
                needId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignNeedManagerDto"];
            };
        };
        responses: {
            /** @description Manager assigned */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coordinator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Need not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationViewDto"][];
                };
            };
        };
    };
    OrganizationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            /** @description Organization created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrganizationResponseDto"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationViewDto"][];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GeocodingController_search: {
        parameters: {
            query: {
                /** @description Address or place name to search */
                q: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Geocoding results (empty array when query is shorter than 3 characters) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResultDto"][];
                };
            };
        };
    };
    MetricsController_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Emergency metrics summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyMetricsDto"];
                };
            };
        };
    };
}
